# Функция нормализации. Сохранение для рассчетов.
Для приложения GUI настроим и сохраним  MinMaxScaler
В приложении будем его готовенький юзать из файла

In [1]:
#import
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import joblib

In [3]:
## Загрузка данных
path  = '../data/raw/ebw_data.csv'
df = pd.read_csv(path) # Датасет не содержит названия столбцов поэтому всталяем реквизит header = None
df.head()

   IW   IF   VW  FP  Depth  Width
0  47  139  4.5  80   1.60   2.54
1  47  139  4.5  80   1.62   2.50
2  47  139  4.5  80   1.68   2.60
3  47  139  4.5  80   1.58   2.52
4  45  140  4.5  80   1.76   2.48

In [9]:
# Разделим выборку на исходные данные и целевые значения
x = df[['IW', 'IF','VW','FP']]
#x.head()
y = df[['Depth', 'Width']]
#y.head()

In [10]:
# Проведем нормализацию данных
std_scaler_x =  MinMaxScaler() 
std_scaler_y =  MinMaxScaler() 
names_x = x.columns # Добудем список имен колонок
names_y = y.columns # Добудем список имен колонок

dataset_x = std_scaler_x.fit_transform(np.array(x[names_x]))
dataset_y = std_scaler_y.fit_transform(np.array(y[names_y]))
scaled_x = pd.DataFrame(dataset_x, columns=names_x) 
scaled_y = pd.DataFrame(dataset_y, columns=names_y) 

#scaled_x # Посмотрим что получилось
#scaled_y # Посмотрим что получилось

In [11]:
# Все путем!
filename_x = '../model/MinMaxScaler_joblib_x.pkl'
filename_y = '../model/MinMaxScaler_joblib_y.pkl'

In [ ]:
# Сохраним объект 
joblib.dump(std_scaler_x, filename_x, compress=9)
joblib.dump(std_scaler_y, filename_y, compress=9)

In [15]:
# Протестим работу сохраненного метода
std_scaler2_x =  joblib.load(filename_x) 
std_scaler2_y =  joblib.load(filename_y)
dataset2_x = std_scaler2_x.fit_transform(np.array(x[names_x]))
dataset2_y = std_scaler2_y.fit_transform(np.array(y[names_y]))
scaled2_x = pd.DataFrame(dataset2_x, columns=names_x) 
scaled2_y = pd.DataFrame(dataset2_y, columns=names_y) 


inverse_x = std_scaler2_x.inverse_transform(np.array(scaled2_x[names_x]))
inverse_y = std_scaler2_y.inverse_transform(np.array(scaled2_y[names_y]))
x2 = pd.DataFrame(inverse_x, columns=names_x) 
y2 = pd.DataFrame(inverse_y, columns=names_y) 


scaled2_x # Посмотрим что получилось
#scaled2_y # Посмотрим что получилось
#x2
#y2

          IW        IF   VW        FP
0   0.666667  0.421053  0.0  0.400000
1   0.666667  0.421053  0.0  0.400000
2   0.666667  0.421053  0.0  0.400000
3   0.666667  0.421053  0.0  0.400000
4   0.333333  0.473684  0.0  0.400000
..       ...       ...  ...       ...
67  0.166667  0.789474  0.6  0.133333
68  0.333333  0.789474  0.6  0.133333
69  0.333333  0.789474  0.6  0.133333
70  0.333333  0.789474  0.6  0.133333
71  0.333333  0.789474  0.6  0.133333

[72 rows x 4 columns]